# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:9500/
Accept: application/json
###

GET http://localhost:9501/
Accept: application/json
###

POST http://localhost:9500/
Content-Type: application/json

{
  "id" : 1,
  "customer" : {
    "customerId" : 1,
    "lastName" : "Wick",
    "firstName" : "John",
    "email" : "john.wick@gmail.com",
    "street" : "Unter den Linden",
    "city" : "Berlin"
  },
  "updated" : "2017-04-20T15:42:12.351+0000",
  "shippingAddress" : {
    "street" : "Ohlauer Str. 43",
    "zip" : "10999",
    "city" : "Berlin"
  },
  "billingAddress" : {
    "street" : "Krischerstr. 100",
    "zip" : "40789",
    "city" : "Monheim am Rhein"
  },
  "orderLine" : [ {
    "count" : 42,
    "item" : {
      "itemId" : 3,
      "name" : "iPod",
      "price" : 42.0
    }
  } ],
  "numberOfLines" : 1,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/order/1"
    },
    "order" : {
      "href" : "http://localhost:8080/order/1"
    }
  }
}
###